name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create env file from secret
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Validate docker-compose file
        run: docker compose --file docker-compose.prod.yml config

      - name: docker compose build
        run: docker compose --file docker-compose.prod.yml build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check required secrets
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          missing=0
          for secret in SSH_PRIVATE_KEY SSH_PORT SSH_USER SSH_HOST ENV_FILE_CONTENT; do
            if [ -z "${!secret}" ]; then
              echo "Secret $secret is not set!"
              missing=1
            fi
          done
          if [ $missing -eq 1 ]; then
            exit 1

      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to server
        run: |
          ssh -i key.pem -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /repos/bolig-kalender
            git pull
            bash re_deploy.sh
          EOF
