name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create env file from secret
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Validate docker-compose file
        run: docker compose --file docker-compose.prod.yml config

      - name: docker compose build
        run: docker compose --file docker-compose.prod.yml build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /bolig-kalender
            git pull
            bash re_deploy.sh
          EOF
